net: DBnet
device_num: 8
eval_start_epoch: 1000
eval_interval: 50
stop_value: {"fmeasure": 0.72}
backbone:
    initializer: mobilenetv3
    pretrained: True
    backbone_ckpt: "./pretrained/mobilenetv3.ckpt" # If on modelarts, set the name of checkpoint saved in data_url
segdetector:
    in_channels: [16, 24, 56, 480]  # R18: [64, 128, 256, 512]
optimizer:
    lr:
        base_lr: 0.02
dataset:
    num_workers: 12
    prefetch_size: 20
train:
    total_epochs: 2000
    batch_size: 8
