net: DBnet
seed: 1
device_num: 1
device_id: 0
per_print_times: 10
run_eval: True
enabel_recovery: False
eval_start_epoch: 100
eval_interval: 20
early_stop: False
stop_value: {"fmeasure": 0.79}
device_target: "None"
context_mode: "graph"
run_profiler: False
mix_precision: True       # Please set it to False on GPU/CPU
ckpt_path: ""
output_dir: "./outputs"
load_mindrecord: True
mindrecord_path: "./dataset"
# Url for modelarts
enable_modelarts: False
data_url: ""
train_url: ""
data_path: "/cache/data"
backbone:
    initializer: resnet18
    pretrained: True
    backbone_ckpt: "./pretrained/resnet18-5c106cde.ckpt" # If on modelarts, set the name of checkpoint saved in data_url
segdetector:
    in_channels: [64, 128, 256, 512]  #R50: [256, 512, 1024, 2048]  R18: [64, 128, 256, 512]
    inner_channels: 256
    k: 50
    bias: False
    adaptive: True
    serial: False
loss:
    eps: 0.000001
    l1_scale: 10
    bce_scale: 5
    bce_replace: bceloss # diceloss / bceloss
optimizer:
    type: momentum
    lr:
        base_lr: 0.007
        target_lr: 0.0
        warmup_epoch: 3
        factor: 0.9
    momentum: 0.9
    weight_decay: 0.0001
dataset:
    type: "IC15"
    is_show: False
    is_icdar2015: True
    num_workers: 12
    prefetch_size: 12
    max_rowsize: 64
    short_side: 736
    random_angle: [-10, 10]
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
    random_crop:
        max_tries: 100
        min_crop_side_ratio: 0.1
train:
    img_format: ['.jpg', '.png', '.JPG', '.PNG']
    img_dir: "~/ICDAR2015/ch4_training_images"  # use abspath
    gt_dir: "~/ICDAR2015/ch4_training_localization_transcription_gt"  # use abspath
    log_filename: train
    pretrained_ckpt: ""
    resume_ckpt: ""  # use abspath
    start_epoch_num: 0
    total_epochs: 1200
    batch_size: 16
    max_checkpoints: 5
    is_transform: True
    train_size: [640, 640]  # [h, w]
    is_eval_before_saving: True
    shrink_ratio: 0.4
    min_text_size: 8
    thresh_min: 0.3
    thresh_max: 0.7
    dataset_sink_mode: True
    clip_grad: False
    force_update: True
eval:
    img_format: ['.jpg', '.png', '.JPG', '.PNG']
    img_dir: "~/ICDAR2015/ch4_test_images"  # use abspath
    gt_dir: "~/ICDAR2015/Challenge4_Test_Task1_GT"  # use abspath
    show_images: False
    image_dir: './outputs_test/'
    thresh: 0.3
    box_thresh: 0.55
    max_candidates: 1000
    unclip_ratio: 1.5
    eval_size: [736, 1280]    # [h, w]
    polygon: False
    dest: binary
