# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
# Path for local
data_path: "/local/data"
output_path: "/local/train"
device_target: "Ascend"

# ==============================================================================
# Training options
epoch_num: 300
run_distribute: "False"
device_id: 0
distribute_epoch_num: 300
pretrained_ckpt: "../resnet34_ascend_v130_imagenet2012_official_cv_bs256_top1acc73.83__top5acc91.61.ckpt"
log_name: "weight01_dink34"
batch_size: 4
learning_rate: 0.0002
model_name: "dinknet34"
scale_factor: 2
scale_window: 1000
init_loss_scale: 16777216

#Eval options
trained_ckpt: "~/dinknet34.ckpt"
label_path: ""
predict_path: ""

# Export options
num_channels: 3
width: 1024
height: 1024
file_name: "dinknet34"
file_format: "MINDIR"

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local"
device_target: "Target device type, available: [Ascend, GPU, CPU]"
batch_size: "Batch size for training and evaluation"

