# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
data_path: "/cache/data"
output_path: "/cache/train"
device_target: "Ascend"
checkpoint_path: "./checkpoint/"
checkpoint_file_path: ""

# ==============================================================================
# Training options
optimizer: "Momentum"
class_num: 10
batch_size: 32
loss_scale: 1024
momentum: 0.9
weight_decay: 0.0001
epoch_size: 180
save_checkpoint: True
save_checkpoint_epochs: 5
keep_checkpoint_max: 10
warmup_epochs: 5
lr_decay_mode: "poly"
lr_init: 0.01
lr_end: 0.00001
lr_max: 0.1
lars_epsilon: 0.0
lars_coefficient: 0.001

net_name: "resnet50"
dataset: "cifar10"
device_num: 1
pre_trained: ""
fp32_ckpt: ""
filter_weight: False
save_best_ckpt: True
mode_name: "GRAPH"
boost_mode: "O0"
conv_init: "XavierUniform"
dense_init: "TruncatedNormal"
all_reduce_fusion_config:
    - 85
    - 160
train_image_size: 224
eval_image_size: 224

comp_algo: "SimQAT"

# Export options
device_id: 0
width: 224
height: 224
file_name: "resnet50"
file_format: "MINDIR"
ckpt_file: ""
network_dataset: "resnet50_cifar10"

# Retrain options
save_graphs: False
save_graphs_path: "./graphs"
has_trained_epoch: 0
has_trained_step: 0

---
# Help description for each configuration
data_url: "Dataset url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local"
device_target: "Target device type, available: [Ascend, GPU, CPU]"
num_classes: "Class for dataset"
batch_size: "Batch size for training and evaluation"
epoch_size: "Total training epochs, should be bigger than has_trained_epoch if retrain."
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
save_graphs: "Whether save graphs during training, default: False."
save_graphs_path: "Path to save graphs."
